#!/bin/bash

#Change list if desired
PACKAGE=("htop" "curl" "wget")

#Check if package is installd by looping over the array to check each one
for package in "${PACKAGE[@]}"; do
    if dpkg -l | grep -Eq "^ii  $package"; then
        sudo apt remove $package
        echo "$package removed"
    else
        echo "package $package is already uninstalled"        
    fi
done